#!/bin/bash 
DOCKER="$1"
if [ "$1" == "" ]; then
    DOCKER=$(docker-compose ps -q)
    echo $DOCKER
    set -f 
    array=(${DOCKER// / })
    if[ "${array[@]}" -eq 1];then
        DOCKER="${array[0]}"
    else
        echo "first param must be container name or id"
        for i in "${!array[@]}"
        do
            echo "${array[i]}"
        done
        exit
    fi
fi

docker exec -i -t $DOCKER bash
