#!/bin/bash
if [ "$1" == "" ]; then
    CLEAN="master"
else
    CLEAN=$1
fi
git checkout $CLEAN
git checkout -- .
git pull --rebase origin $CLEAN
git reset --hard origin/$CLEAN
chown -Rf $USER:$USER .
